language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=pypy
  - TOX_ENV=flake8
install:
  - "sudo apt-get -qq update"
  - "sudo apt-get -y install pkg-config libsmi2-dev libsnmp-dev snmp-mibs-downloader"
  # Solution to travis issue #155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  - pip install tox coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
