language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
  - TOX_ENV=lint
  - TOX_ENV=doc
install:
  # This is required because we need to get rid of the Travis installed PyPy
  # or it'll take precedence over the PPA installed one.
  - "[[ ${TOX_ENV} != pypy ]] || sudo add-apt-repository -y ppa:pypy/ppa"
  - "[[ ${TOX_ENV} != pypy ]] || sudo apt-get -y update && sudo apt-get -y install pypy"
  - "[[ ${TOX_ENV} != pypy ]] || sudo rm -rf /opt/python/pypy*"
  - "[[ ${TOX_ENV} != pypy ]] || pypy --version"
  - "sudo apt-get -qq update"
  - "sudo apt-get -y install pkg-config libsmi2-dev libsnmp-dev snmp-mibs-downloader ncurses-term"
  - pip install tox coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
