language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
  - TOX_ENV=lint
  - TOX_ENV=doc
install:
  - "sudo apt-get -qq update"
  - "sudo apt-get -y install pkg-config libsmi2-dev libsnmp-dev snmp-mibs-downloader"
  - pip install tox coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
